version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4-node-browsers

    steps:
      - checkout

      - run:
          name: "Prepare Environment"
          command: |
            sudo apt update
            sudo docker-php-ext-install zip

      - run:
          name: "Create Environment file"
          command: |
            mv .env.testing .env

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # prepare the database
      - run:
          name: "Generate app key"
          command: php artisan key:generate

#      - run:
#          name: "Create database"
#          command: touch database/test.sqlite
#
#      - run:
#          name: "Run migration"
#          command: php artisan migrate
#
#      - run:
#          name: "Run migration"
#          command: php artisan config:cache

      # run tests with phpunit
      - run:
          name: "Run Tests"
          command: vendor/bin/phpunit
